;;; fleet-theme.el --- Fleet theme using modus-themes overrides -*- lexical-binding: t; -*-

;;; Commentary:
;; Fleet theme colors adapted for modus-themes palette overrides

;;; Code:

(use-package modus-themes
  :ensure nil
  :defer t
  :custom
  (modus-themes-italic-constructs t)
  (modus-themes-bold-constructs t)
  (modus-themes-mixed-fonts nil)
  (modus-themes-prompts '(bold intense))
  (modus-themes-common-palette-overrides
   `((bg-main "#181818")
     (bg-active "#1C1C1C")
     (fg-main "#EFEFEF")
     (fg-active "#FFFFFF")
     (fg-mode-line-active "#EFEFEF")
     (bg-mode-line-active "#1C1C1C")
     (fg-mode-line-inactive "#5D5D5D")
     (bg-mode-line-inactive "#1C1C1C")
     (border-mode-line-active nil)
     (border-mode-line-inactive nil)
     (bg-tab-bar "#181818")
     (bg-tab-current bg-main)
     (bg-tab-other "#181818")
     (fg-prompt "#ECA775")
     (bg-prompt "#181818")
     (bg-hover-secondary "#353535")
     (bg-completion "#163764")
     (fg-completion "#EFEFEF")
     (bg-region "#2A2A2A")
     (fg-region unspecified)

     (fg-line-number-active "#D1D1D1")
     (fg-line-number-inactive "#5D5D5D")
     (bg-line-number-active "#1C1C1C")
     (bg-line-number-inactive "#181818")
     (fringe "#181818")

     (fg-heading-0 "#94C1FA")
     (fg-heading-1 "#94C1FA")
     (fg-heading-2 "#AC9CF9")
     (fg-heading-3 "#D898D8")
     (fg-heading-4 "#94C1FA")

     (fg-prose-verbatim "#D898D8")
     (bg-prose-block-contents "#1C1C1C")
     (fg-prose-block-delimiter "#898989")
     (bg-prose-block-delimiter bg-prose-block-contents)

     (accent-1 "#78D0BD")

     (keyword "#78D0BD")
     (builtin "#78D0BD")
     (comment "#898989")
     (string "#D898D8")
     (fnname "#E5C995")
     (type "#94C1FA")
     (variable "#EFEFEF")
     (docstring "#898989")
     (constant "#E5C995")
     
     (cursor "#FFFFFF")))
  :config
  (modus-themes-with-colors
    (custom-set-faces
     `(tab-bar ((,c :background "#181818" :foreground "#5D5D5D" :box nil)))
     `(tab-bar-tab ((,c :background "#1C1C1C" :foreground "#EFEFEF"
                          :box (:line-width 1 :color "#353535")
                          :weight medium)))
     `(tab-bar-tab-inactive ((,c :background "#181818" :foreground "#5D5D5D"
                                 :box (:line-width 1 :color "#181818"))))
     `(tab-bar-tab-group-current ((,c :background "#181818" :foreground "#EFEFEF" :box nil)))
     `(tab-bar-tab-group-inactive ((,c :background "#181818" :foreground "#5D5D5D" :box nil)))
     `(icomplete-first-match ((,c :foreground "#78D0BD" :weight bold)))
     `(completions-highlight ((,c :background "#163764" :foreground "#EFEFEF")))
     `(completions-common-part ((,c :foreground "#78D0BD")))
     `(completions-first-difference ((,c :foreground "#D898D8")))
     `(dired-directory ((,c :foreground "#94C1FA")))
     `(dired-symlink ((,c :foreground "#78D0BD" :italic t)))
     `(dired-marked ((,c :foreground "#E5C995" :weight bold)))
     `(dired-flagged ((,c :foreground "#FF6B6B" :weight bold)))
     `(dired-header ((,c :foreground "#AC9CF9" :weight bold)))
     `(dired-ignored ((,c :foreground "#5D5D5D")))
     `(dired-perm-write ((,c :foreground "#ECA775")))

     ;; eshell
     `(eshell-prompt ((,c :foreground "#ECA775" :weight bold)))
     `(eshell-ls-directory ((,c :foreground "#94C1FA" :weight bold)))
     `(eshell-ls-executable ((,c :foreground "#78D0BD")))
     `(eshell-ls-symlink ((,c :foreground "#78D0BD" :italic t)))
     `(eshell-ls-archive ((,c :foreground "#D898D8")))
     `(eshell-ls-readonly ((,c :foreground "#898989")))

     ;; eat (ANSI terminal colors)
     `(eat-term-color-0 ((,c :foreground "#181818" :background "#181818")))
     `(eat-term-color-1 ((,c :foreground "#FF6B6B" :background "#FF6B6B")))
     `(eat-term-color-2 ((,c :foreground "#78D0BD" :background "#78D0BD")))
     `(eat-term-color-3 ((,c :foreground "#E5C995" :background "#E5C995")))
     `(eat-term-color-4 ((,c :foreground "#94C1FA" :background "#94C1FA")))
     `(eat-term-color-5 ((,c :foreground "#D898D8" :background "#D898D8")))
     `(eat-term-color-6 ((,c :foreground "#78D0BD" :background "#78D0BD")))
     `(eat-term-color-7 ((,c :foreground "#D1D1D1" :background "#D1D1D1")))
     `(eat-term-color-8 ((,c :foreground "#5D5D5D" :background "#5D5D5D")))
     `(eat-term-color-9 ((,c :foreground "#FF8F8F" :background "#FF8F8F")))
     `(eat-term-color-10 ((,c :foreground "#99DDCC" :background "#99DDCC")))
     `(eat-term-color-11 ((,c :foreground "#ECD6A8" :background "#ECD6A8")))
     `(eat-term-color-12 ((,c :foreground "#B4D4FC" :background "#B4D4FC")))
     `(eat-term-color-13 ((,c :foreground "#E4B8E4" :background "#E4B8E4")))
     `(eat-term-color-14 ((,c :foreground "#99DDCC" :background "#99DDCC")))
     `(eat-term-color-15 ((,c :foreground "#EFEFEF" :background "#EFEFEF")))

     ;; vterm (ANSI terminal colors)
     `(vterm-color-default ((,c :foreground "#EFEFEF" :background "#181818")))
     `(vterm-color-black ((,c :foreground "#181818" :background "#181818")))
     `(vterm-color-red ((,c :foreground "#FF6B6B" :background "#FF6B6B")))
     `(vterm-color-green ((,c :foreground "#78D0BD" :background "#78D0BD")))
     `(vterm-color-yellow ((,c :foreground "#E5C995" :background "#E5C995")))
     `(vterm-color-blue ((,c :foreground "#94C1FA" :background "#94C1FA")))
     `(vterm-color-magenta ((,c :foreground "#D898D8" :background "#D898D8")))
     `(vterm-color-cyan ((,c :foreground "#78D0BD" :background "#78D0BD")))
     `(vterm-color-white ((,c :foreground "#D1D1D1" :background "#D1D1D1")))
     `(vterm-color-bright-black ((,c :foreground "#5D5D5D" :background "#5D5D5D")))
     `(vterm-color-bright-red ((,c :foreground "#FF8F8F" :background "#FF8F8F")))
     `(vterm-color-bright-green ((,c :foreground "#99DDCC" :background "#99DDCC")))
     `(vterm-color-bright-yellow ((,c :foreground "#ECD6A8" :background "#ECD6A8")))
     `(vterm-color-bright-blue ((,c :foreground "#B4D4FC" :background "#B4D4FC")))
     `(vterm-color-bright-magenta ((,c :foreground "#E4B8E4" :background "#E4B8E4")))
     `(vterm-color-bright-cyan ((,c :foreground "#99DDCC" :background "#99DDCC")))
     `(vterm-color-bright-white ((,c :foreground "#EFEFEF" :background "#EFEFEF")))
     `(vterm-color-underline ((,c :underline t)))
     `(vterm-color-inverse-video ((,c :background "#353535")))

     ;; isearch
     `(isearch ((,c :background "#163764" :foreground "#FFFFFF" :weight bold)))
     `(lazy-highlight ((,c :background "#353535" :foreground "#EFEFEF")))
     `(isearch-fail ((,c :background "#5C1A1A" :foreground "#FF6B6B")))

     ;; diff
     `(diff-added ((,c :background "#1A3A1A" :foreground "#99DDCC")))
     `(diff-removed ((,c :background "#3A1A1A" :foreground "#FF8F8F")))
     `(diff-changed ((,c :background "#2A2A1A" :foreground "#E5C995")))
     `(diff-header ((,c :foreground "#94C1FA" :weight bold)))
     `(diff-file-header ((,c :foreground "#AC9CF9" :weight bold)))
     `(diff-refine-added ((,c :background "#2A5A2A" :foreground "#99DDCC")))
     `(diff-refine-removed ((,c :background "#5C1A1A" :foreground "#FF8F8F")))

     ;; magit
     `(magit-section-highlight ((,c :background "#1C1C1C")))
     `(magit-section-heading ((,c :foreground "#94C1FA" :weight bold)))
     `(magit-section-secondary-heading ((,c :foreground "#AC9CF9" :weight bold)))
     `(magit-section-heading-selection ((,c :foreground "#E5C995" :weight bold)))
     `(magit-dimmed ((,c :foreground "#5D5D5D")))
     `(magit-hash ((,c :foreground "#898989")))
     `(magit-tag ((,c :foreground "#D898D8")))
     `(magit-branch-local ((,c :foreground "#94C1FA")))
     `(magit-branch-remote ((,c :foreground "#78D0BD")))
     `(magit-branch-current ((,c :foreground "#E5C995" :weight bold)))
     `(magit-branch-remote-head ((,c :foreground "#78D0BD" :weight bold)))
     `(magit-branch-upstream ((,c :foreground "#AC9CF9")))
     `(magit-branch-warning ((,c :foreground "#FF6B6B" :weight bold)))
     `(magit-head ((,c :foreground "#ECA775" :weight bold)))
     `(magit-refname ((,c :foreground "#D1D1D1")))
     `(magit-refname-stash ((,c :foreground "#D898D8")))
     `(magit-refname-wip ((,c :foreground "#ECA775")))
     `(magit-refname-pullreq ((,c :foreground "#AC9CF9")))
     `(magit-keyword ((,c :foreground "#78D0BD")))
     `(magit-keyword-squash ((,c :foreground "#D898D8" :weight bold)))
     `(magit-signature-good ((,c :foreground "#78D0BD" :weight bold)))
     `(magit-signature-bad ((,c :foreground "#FF6B6B" :weight bold)))
     `(magit-signature-untrusted ((,c :foreground "#E5C995" :weight bold)))
     `(magit-signature-expired ((,c :foreground "#ECA775")))
     `(magit-signature-expired-key ((,c :foreground "#ECA775")))
     `(magit-signature-revoked ((,c :foreground "#FF6B6B")))
     `(magit-signature-error ((,c :foreground "#FF6B6B" :weight bold)))
     `(magit-cherry-unmatched ((,c :foreground "#78D0BD")))
     `(magit-cherry-equivalent ((,c :foreground "#D898D8")))
     `(magit-filename ((,c :foreground "#EFEFEF")))
     `(magit-header-line ((,c :background "#1C1C1C" :foreground "#EFEFEF"
                             :box (:line-width 1 :color "#353535"))))
     `(magit-header-line-key ((,c :foreground "#ECA775" :weight bold)))
     `(magit-diff-file-heading ((,c :foreground "#EFEFEF" :weight medium)))
     `(magit-diff-file-heading-highlight ((,c :background "#1C1C1C" :foreground "#EFEFEF")))
     `(magit-diff-file-heading-selection ((,c :background "#163764" :foreground "#FFFFFF" :weight bold)))
     `(magit-diff-hunk-heading ((,c :background "#1C1C1C" :foreground "#898989")))
     `(magit-diff-hunk-heading-highlight ((,c :background "#2A2A2A" :foreground "#D1D1D1")))
     `(magit-diff-hunk-heading-selection ((,c :background "#163764" :foreground "#FFFFFF" :weight bold)))
     `(magit-diff-conflict-heading ((,c :background "#5C1A1A" :foreground "#FF8F8F" :weight bold)))
     `(magit-diff-conflict-heading-highlight ((,c :background "#6A2424" :foreground "#FF8F8F" :weight bold)))
     `(magit-diff-revision-summary ((,c :foreground "#94C1FA" :weight bold)))
     `(magit-diff-revision-summary-highlight ((,c :background "#1C1C1C" :foreground "#94C1FA" :weight bold)))
     `(magit-diff-lines-heading ((,c :background "#2A2A1A" :foreground "#E5C995")))
     `(magit-diff-context ((,c :background "#181818" :foreground "#D1D1D1")))
     `(magit-diff-context-highlight ((,c :background "#1C1C1C" :foreground "#EFEFEF")))
     `(magit-diff-added ((,c :inherit diff-added)))
     `(magit-diff-added-highlight ((,c :background "#2A5A2A" :foreground "#99DDCC")))
     `(magit-diff-removed ((,c :inherit diff-removed)))
     `(magit-diff-removed-highlight ((,c :background "#5C1A1A" :foreground "#FF8F8F")))
     `(magit-diff-our ((,c :inherit magit-diff-removed)))
     `(magit-diff-base ((,c :background "#2A2A1A" :foreground "#E5C995")))
     `(magit-diff-their ((,c :inherit magit-diff-added)))
     `(magit-diff-our-highlight ((,c :inherit magit-diff-removed-highlight)))
     `(magit-diff-base-highlight ((,c :background "#353515" :foreground "#ECD6A8")))
     `(magit-diff-their-highlight ((,c :inherit magit-diff-added-highlight)))
     `(magit-diff-added-indicator ((,c :foreground "#78D0BD" :background "#1A3A1A")))
     `(magit-diff-removed-indicator ((,c :foreground "#FF6B6B" :background "#3A1A1A")))
     `(magit-diff-our-indicator ((,c :inherit magit-diff-removed-indicator)))
     `(magit-diff-base-indicator ((,c :foreground "#E5C995" :background "#2A2A1A")))
     `(magit-diff-their-indicator ((,c :inherit magit-diff-added-indicator)))
     `(magit-diffstat-added ((,c :foreground "#78D0BD")))
     `(magit-diffstat-removed ((,c :foreground "#FF6B6B")))
     `(magit-diff-hunk-region ((,c :background "#2A2A2A")))
     `(magit-diff-whitespace-warning ((,c :background "#5C1A1A" :foreground "#FF8F8F")))
     `(magit-log-author ((,c :foreground "#ECA775")))
     `(magit-log-date ((,c :foreground "#898989")))
     `(magit-log-graph ((,c :foreground "#5D5D5D")))
     `(magit-process-ok ((,c :foreground "#78D0BD" :weight bold)))
     `(magit-process-ng ((,c :foreground "#FF6B6B" :weight bold)))
     `(magit-mode-line-process ((,c :foreground "#78D0BD")))
     `(magit-mode-line-process-error ((,c :foreground "#FF6B6B" :weight bold)))
     `(magit-blame-heading ((,c :background "#1C1C1C" :foreground "#898989")))
     `(magit-blame-highlight ((,c :background "#2A2A2A" :foreground "#D1D1D1")))
     `(magit-blame-margin ((,c :background "#1C1C1C" :foreground "#898989")))
     `(magit-blame-dimmed ((,c :background "#181818" :foreground "#5D5D5D")))
     `(magit-sequence-pick ((,c :foreground "#78D0BD")))
     `(magit-sequence-stop ((,c :foreground "#E5C995")))
     `(magit-sequence-part ((,c :foreground "#ECA775")))
     `(magit-sequence-head ((,c :foreground "#94C1FA")))
     `(magit-sequence-drop ((,c :foreground "#FF6B6B")))
     `(magit-sequence-done ((,c :foreground "#5D5D5D")))
     `(magit-sequence-onto ((,c :foreground "#AC9CF9")))
     `(magit-sequence-exec ((,c :foreground "#D898D8")))
     `(magit-bisect-good ((,c :foreground "#78D0BD" :weight bold)))
     `(magit-bisect-skip ((,c :foreground "#E5C995" :weight bold)))
     `(magit-bisect-bad ((,c :foreground "#FF6B6B" :weight bold)))
     `(magit-reflog-commit ((,c :foreground "#78D0BD")))
     `(magit-reflog-amend ((,c :foreground "#D898D8")))
     `(magit-reflog-merge ((,c :foreground "#78D0BD")))
     `(magit-reflog-checkout ((,c :foreground "#94C1FA")))
     `(magit-reflog-reset ((,c :foreground "#FF6B6B")))
     `(magit-reflog-rebase ((,c :foreground "#D898D8")))
     `(magit-reflog-cherry-pick ((,c :foreground "#78D0BD")))
     `(magit-reflog-remote ((,c :foreground "#AC9CF9")))
     `(magit-reflog-other ((,c :foreground "#ECA775")))
     `(git-commit-summary ((,c :foreground "#EFEFEF")))
     `(git-commit-overlong-summary ((,c :foreground "#FF6B6B" :weight bold)))
     `(git-commit-nonempty-second-line ((,c :foreground "#E5C995" :weight bold)))
     `(git-commit-keyword ((,c :foreground "#78D0BD")))
     `(git-commit-trailer-token ((,c :foreground "#94C1FA" :weight bold)))
     `(git-commit-trailer-value ((,c :foreground "#D1D1D1")))
     `(git-commit-comment-heading ((,c :foreground "#898989")))
     `(git-commit-comment-branch-local ((,c :foreground "#94C1FA")))
     `(git-commit-comment-branch-remote ((,c :foreground "#78D0BD")))
     `(git-commit-comment-detached ((,c :foreground "#ECA775")))
     `(git-commit-comment-action ((,c :foreground "#D898D8")))
     `(git-commit-comment-file ((,c :foreground "#EFEFEF")))
     `(git-commit-comment-button ((,c :foreground "#AC9CF9" :underline t)))

     ;; transient
     `(transient-heading ((,c :foreground "#94C1FA" :weight bold)))
     `(transient-key ((,c :foreground "#ECA775" :weight bold)))
     `(transient-key-exit ((,c :foreground "#FF6B6B" :weight bold)))
     `(transient-key-return ((,c :foreground "#78D0BD" :weight bold)))
     `(transient-key-recurse ((,c :foreground "#AC9CF9" :weight bold)))
     `(transient-key-stack ((,c :foreground "#D898D8" :weight bold)))
     `(transient-argument ((,c :foreground "#E5C995" :weight bold)))
     `(transient-value ((,c :foreground "#78D0BD" :weight bold)))
     `(transient-active-infix ((,c :background "#1C1C1C" :foreground "#EFEFEF")))
     `(transient-enabled-suffix ((,c :foreground "#78D0BD" :weight bold)))
     `(transient-disabled-suffix ((,c :foreground "#5D5D5D")))
     `(transient-inactive-argument ((,c :foreground "#5D5D5D")))
     `(transient-inactive-value ((,c :foreground "#5D5D5D")))
     `(transient-inapt-argument ((,c :foreground "#898989")))
     `(transient-inapt-suffix ((,c :foreground "#898989" :slant italic)))
     `(transient-unreachable ((,c :foreground "#5D5D5D")))
     `(transient-unreachable-key ((,c :foreground "#5D5D5D")))
     `(transient-nonstandard-key ((,c :foreground "#D898D8" :weight bold)))
     `(transient-mismatched-key ((,c :foreground "#FF6B6B" :weight bold)))
     `(transient-delimiter ((,c :foreground "#5D5D5D")))

     ;; flymake
     `(flymake-error ((,c :underline (:style wave :color "#FF6B6B"))))
     `(flymake-warning ((,c :underline (:style wave :color "#E5C995"))))
     `(flymake-note ((,c :underline (:style wave :color "#78D0BD"))))

     ;; markdown
     `(markdown-header-face-1 ((,c :foreground "#94C1FA" :weight bold)))
     `(markdown-header-face-2 ((,c :foreground "#AC9CF9" :weight bold)))
     `(markdown-header-face-3 ((,c :foreground "#D898D8" :weight bold)))
     `(markdown-header-face-4 ((,c :foreground "#94C1FA" :weight bold)))
     `(markdown-header-face-5 ((,c :foreground "#AC9CF9" :weight bold)))
     `(markdown-header-face-6 ((,c :foreground "#D898D8" :weight bold)))
     `(markdown-header-delimiter-face ((,c :foreground "#898989")))
     `(markdown-markup-face ((,c :foreground "#898989")))
     `(markdown-code-face ((,c :foreground "#D898D8" :background "#1C1C1C")))
     `(markdown-inline-code-face ((,c :foreground "#D898D8" :background "#1C1C1C")))
     `(markdown-pre-face ((,c :foreground "#D898D8" :background "#1C1C1C")))
     `(markdown-language-keyword-face ((,c :foreground "#78D0BD")))
     `(markdown-url-face ((,c :foreground "#AC9CF9")))
     `(markdown-link-face ((,c :foreground "#94C1FA")))
     `(markdown-bold-face ((,c :foreground "#EFEFEF" :weight bold)))
     `(markdown-italic-face ((,c :foreground "#EFEFEF" :slant italic)))
     `(markdown-blockquote-face ((,c :foreground "#898989" :slant italic)))
     `(markdown-list-face ((,c :foreground "#78D0BD")))
     `(markdown-hr-face ((,c :foreground "#5D5D5D")))

     ;; org
     `(org-todo ((,c :foreground "#FF6B6B" :weight bold)))
     `(org-done ((,c :foreground "#78D0BD" :weight bold)))
     `(org-date ((,c :foreground "#AC9CF9" :underline t)))
     `(org-tag ((,c :foreground "#898989" :weight normal)))
     `(org-link ((,c :foreground "#94C1FA" :underline t)))))
  :init
  (load-theme 'modus-vivendi-tinted t))

(provide 'fleet-theme)

;;; fleet-theme.el ends here
